<?php

/**
 * Created by PhpStorm.
 * User: Aleksander
 * Date: 13/01/2017
 * Time: 12:05
 */
require_once 'text.php';
class ctext extends text
{
    var $color = false;

    function setColor($c){
        $this->color = $c;
    }
    function show()
    {
        if($this->color ===false){
            parent::show(); // TODO: Change the autogenerated stub
        }else{
            echo '<font color="'.$this->color.'">'.$this->str.'</font></br>';
        }
    }
}